# 모두를 위한 딥러닝 : Pytorch
## Lecture 1-1,2 - Tensor Manipulation
본 문서는 모두를 위한 딥러닝 강의를 듣고 공부 목적으로 작성되었습니다.

In [1]:
import numpy as np
import torch.nn as nn
import torch

먼저, 기존 numpy를 복습해보겠다.  

### 1D Array with Numpy

In [2]:
t= np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print("Rank of t : ",t.ndim)
print("Shape of t : ", t.shape)

Rank of t :  1
Shape of t :  (7,)


In [4]:
print(t[0], t[1:4])

0.0 [1. 2. 3.]


### 2D Array with NumPy

In [5]:
t= np.array([[1,2,3], [4,5,6], [7,8,9]])

In [6]:
print("Rank of t : ", t.ndim)
print("Shape of t : ", t.shape)

Rank of t :  2
Shape of t :  (3, 3)


Pytorch도 Numpy와 비슷하다. 하지만, 더 좋다.  

### 1D array with Pytorch

In [7]:
t = torch.FloatTensor([0,1,2,3,4,5,6])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [8]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0],t[1],t[-1])
print(t[2:5], t[4:-1])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])


### 2D Array with Pytorch

In [9]:
t= torch.FloatTensor([[1,2,3],
[4,5,6],
[7,8,9],
[10,11,12]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[:,1])
print(t[:,1].shape)
print(t[:,:-1])

2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Shape, Rank, Axis

In [11]:
t = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]
                       ]])

In [12]:
print(t.dim())
print(t.shape)
print(t.size())

4
torch.Size([1, 2, 3, 4])
torch.Size([1, 2, 3, 4])


### Frequently Used Operations in Pytorch
파이토치에서 주로 사용되는 연산자를 살펴보겠다.
#### Mul vs. MatMul
(1)MatMul

In [13]:
print()
print('-------')
print('Mul vs Matmul')
print('-------')
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('m1 : ', m1)
print('m2 : ', m2)
print(m1.shape)
print(m2.shape)
print(m1.matmul(m2))


-------
Mul vs Matmul
-------
m1 :  tensor([[1., 2.],
        [3., 4.]])
m2 :  tensor([[1.],
        [2.]])
torch.Size([2, 2])
torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


(2) Mul

In [14]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('m1 : ', m1)
print('m2 : ', m2)
print(m1*m2)
print(m1.mul(m2))

m1 :  tensor([[1., 2.],
        [3., 4.]])
m2 :  tensor([[1.],
        [2.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


Matmul은 행렬곱을 진행해주고, Mul은 같은 차원에 있는 원소들을 곱해준다.

#### BroadCasting

In [15]:
# 같은 shape를 가진 두 행렬은 더할 수 있다.
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [16]:
# 1차원 scalar 텐서에 대해서, broadcasting을 통해 shape를 맞춰준 후, 행렬의 덧셈을 진행한다.
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(m1+m2)

tensor([[4., 5.]])


In [17]:
# 모양이 다른 두 개의 행렬도 size를 맞춰준 후, 덧셈을 진행한다.
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


### Mean

In [18]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


유의할 점은 정수 텐서(Long Tensor)에 대해서는 평균을 적용할 수 없다.

In [19]:
t = torch.LongTensor([1,3])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [20]:
## 차원을 지정하여, 평균을 구할 수 있다.
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [21]:
print(t.mean())
print(t.mean(dim=0)) #나머지 차원에 대해서는 고정!
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### Sum
합도 마찬가지로, 차원을 지정해서 할 수 있다.

In [22]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])


### Max and ArgMax

In [23]:
print(t.max())
print(t.max(dim=0))
print(t.max(dim=1))
print(t.max(dim=-1))

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [24]:
print("Max : ", t.max(dim=1)[0])
print("Arg Max : ", t.max(dim=1)[1])

Max :  tensor([2., 4.])
Arg Max :  tensor([1, 1])


### View
알아두면 매우 유용한 함수이다. Shape를 변경할 때, 많이 사용하는데, 원하는 차원의 shape를 지정해두고, 나머지는 -1로 설정한다.

In [25]:
t = np.array([[[0,1,2],
                [3,4,5]],
                [[6,7,8],
                [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [26]:
print(ft.view([-1,3]))
print(ft.view([-1,3,2]))

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.]],

        [[ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]]])


In [27]:
print(ft.view([-1,3]).shape)
print(ft.view([-1,3,2]).shape)

torch.Size([4, 3])
torch.Size([2, 3, 2])


### Squeeze
차원을 줄여주는 함수이다.

In [28]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [29]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


# UnSqueeze
반대로 차원을 늘려주는 함수이다. 행렬의 연산을 위해 많이 쓰인다.

In [31]:
ft = torch.FloatTensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [32]:
print(ft.unsqueeze(dim=1))
print(ft.unsqueeze(dim=1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [33]:
print(ft.unsqueeze(dim=0))
print(ft.unsqueeze(dim=0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


### Type Casting
자료형을 변환해준다.

In [36]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [37]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [38]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [39]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenate
두개의 행렬을 이어붙여준다. rack는 변하지 않는다.

In [40]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [41]:
print(torch.cat([x,y],dim=0))
print(torch.cat([x,y],dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking
여러 개의 행렬을 쌓아주는 역할을 한다. rank가 변한다. 지정해준 차원으로 unsqueeze를 진행한 후, 쌓는다고 생각하면 될 것이다.

In [43]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim = 1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [44]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Ones and Zeros Like
주어진 텐서와 같은 모양을 가진 1텐서나 0텐서를 만든다.

In [45]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [47]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-Place Operation
함수적용만 할 것인지, 함수 적용해 나온 return값을 메모리에 재할당할 것인지 결정한다.

In [48]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [49]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


### 그 밖의 기본적으로 알면 좋은 것들
#### Zip

In [51]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [52]:
for x, y in zip(*[[1, 2, 3], [4, 5, 6]]):
    print(x, y)

1 4
2 5
3 6


별표의 역할도 기억해두자