# 모두를 위한 딥러닝 : Pytorch
## Lecture 4-2 - Load Data
본 문서는 모두를 위한 딥러닝 강의를 듣고 공부 목적으로 작성되었습니다.

### Slicing 1D Array

In [1]:
nums = [0, 1, 2, 3, 4]

In [2]:
print(nums)

[0, 1, 2, 3, 4]


In [3]:
print(nums[2:4])

[2, 3]


### Slicing 2D Array

In [4]:
import numpy as np

In [5]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [6]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
b[:,1] # 2D -> 1D

array([ 2,  6, 10])

In [10]:
b[:,1:2] #차원 유지

array([[ 2],
       [ 6],
       [10]])

### Loading Data from .csv File

In [11]:
import numpy as np

In [13]:
xy = np.loadtxt('./data-01-test-score.csv', delimiter = ',', dtype = np.float32)

In [14]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]] #차원 유지를 위해

In [15]:
print(x_data.shape) # x_data shape
print(len(x_data))  # x_data 길이
print(x_data[:5])

(25, 3)
25
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]


In [17]:
print(y_data.shape) # y_data shape
print(len(y_data))  # y_data 길이
print(y_data[:5])

(25, 1)
25
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


In [18]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

### Low Level Implementation

In [19]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    hypothesis = x_train.matmul(W) + b # or .mm or @

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/20 Cost: 26811.960938
Epoch    1/20 Cost: 9920.530273
Epoch    2/20 Cost: 3675.298828
Epoch    3/20 Cost: 1366.260498
Epoch    4/20 Cost: 512.542480
Epoch    5/20 Cost: 196.896667
Epoch    6/20 Cost: 80.190987
Epoch    7/20 Cost: 37.038689
Epoch    8/20 Cost: 21.081348
Epoch    9/20 Cost: 15.178763
Epoch   10/20 Cost: 12.993682
Epoch   11/20 Cost: 12.183030
Epoch   12/20 Cost: 11.880535
Epoch   13/20 Cost: 11.765960
Epoch   14/20 Cost: 11.720860
Epoch   15/20 Cost: 11.701432
Epoch   16/20 Cost: 11.691512
Epoch   17/20 Cost: 11.685116
Epoch   18/20 Cost: 11.680002
Epoch   19/20 Cost: 11.675382
Epoch   20/20 Cost: 11.670952


### High Level Implementation with nn.Module

In [20]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)

In [21]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)
# 모델 초기화
model = MultivariateLinearRegressionModel()
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs+1):
    
    # H(x) 계산
    prediction = model(x_train)
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 20번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/20 Cost: 13585.458984
Epoch    1/20 Cost: 5027.791016
Epoch    2/20 Cost: 1863.783691
Epoch    3/20 Cost: 693.962280
Epoch    4/20 Cost: 261.446259
Epoch    5/20 Cost: 101.532845
Epoch    6/20 Cost: 42.407536
Epoch    7/20 Cost: 20.546978
Epoch    8/20 Cost: 12.463853
Epoch    9/20 Cost: 9.474754
Epoch   10/20 Cost: 8.369058
Epoch   11/20 Cost: 7.959688
Epoch   12/20 Cost: 7.807773
Epoch   13/20 Cost: 7.751040
Epoch   14/20 Cost: 7.729488
Epoch   15/20 Cost: 7.720986
Epoch   16/20 Cost: 7.717251
Epoch   17/20 Cost: 7.715328
Epoch   18/20 Cost: 7.714064
Epoch   19/20 Cost: 7.713014
Epoch   20/20 Cost: 7.712068
